spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5000/pms
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true


billing:
  service:
    address: localhost
    port: 3001

server:
  port: 3000
